export const JOB_CATEGORIES = [
  "Backend",
  "Frontend",
  "Fullstack",
  "DevOps",
  "Data/AI",
  "Machine Learning",
  "QA",
  "Cyber",
  "Mobile",
  "Embedded",
  "Product",
  "UX/Design",
  "Software Architect",
  "R&D Management",
  "IT",
  "Hardware",
  "Mechanical Engineering",
  "Project Management",
  "Data Analyst",
  "Sales",
  "Marketing",
  "HR",
  "Finance",
  "Customer Success",
  "Legal",
  "Student Jobs",
  "Freelance",
  "Electrical Engineering",
  "Robotics",
  "Security Research",
  "Solution Engineering",
  "Content Writing",
  "Operations",
  "Executive Roles",
] as const

export type JobCategory = (typeof JOB_CATEGORIES)[number]

export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  Backend: [
    "backend",
    "back-end",
    "backend developer",
    "backend engineer",
    "server-side developer",
    "api developer",
    "מפתח בקאנד",
    "מפתח שרת",
    "java developer",
    "python developer",
    "node developer",
    "nodejs developer",
    "django developer",
    "fastapi developer",
    "spring developer",
    ".net developer",
    "golang developer",
  ],
  Frontend: [
    "frontend",
    "front-end",
    "frontend developer",
    "frontend engineer",
    "front-end developer",
    "ui developer",
    "react developer",
    "angular developer",
    "vue developer",
    "מפתח פרונטאנד",
    "web developer",
    "javascript developer",
    "typescript developer",
  ],
  Fullstack: [
    "fullstack",
    "full stack",
    "full-stack",
    "full-stack developer",
    "fullstack developer",
    "fullstack engineer",
    "full stack developer",
    "full stack engineer",
    "full-stack engineer",
    "פולסטאק",
    "מפתח פולסטאק",
  ],
  DevOps: [
    "devops",
    "devops engineer",
    "dev ops",
    "platform engineer",
    "site reliability engineer",
    "sre",
    "cloud engineer",
    "infrastructure engineer",
    "devsecops",
    "mlops engineer",
    "build engineer",
    "release engineer",
  ],
  "Data/AI": [
    "data scientist",
    "data engineer",
    "ml engineer",
    "machine learning engineer",
    "ai engineer",
    "deep learning engineer",
    "nlp engineer",
    "computer vision engineer",
    "מדען נתונים",
    "מהנדס נתונים",
    "data platform engineer",
  ],
  "Machine Learning": [
    "machine learning engineer",
    "ml engineer",
    "deep learning engineer",
    "research scientist",
    "ai researcher",
    "ml researcher",
    "mlops",
    "computer vision engineer",
    "nlp engineer",
  ],
  QA: [
    "qa engineer",
    "quality assurance engineer",
    "test engineer",
    "automation engineer",
    "sdet",
    "software tester",
    "manual tester",
    "qa tester",
    "בודק תוכנה",
    "quality engineer",
  ],
  Cyber: [
    "cyber security engineer",
    "security engineer",
    "penetration tester",
    "pen tester",
    "soc analyst",
    "information security engineer",
    "infosec engineer",
    "cybersecurity engineer",
    "security researcher",
    "vulnerability researcher",
    "אבטחת מידע",
  ],
  Mobile: [
    "mobile developer",
    "ios developer",
    "android developer",
    "mobile engineer",
    "react native developer",
    "flutter developer",
    "swift developer",
    "kotlin developer",
    "מפתח מובייל",
  ],
  Embedded: [
    "embedded developer",
    "embedded engineer",
    "firmware engineer",
    "embedded software engineer",
    "rtos developer",
    "embedded linux engineer",
    "מפתח מוטמע",
  ],
  Product: [
    "product manager", "pm", "product owner",
    "מנהל מוצר", "product lead", "head of product",
    "group product manager", "senior product manager",
  ],
  "UX/Design": [
    "ux designer", "ui designer", "product designer", "figma",
    "user experience designer", "interaction designer",
    "מעצב מוצר", "graphic designer", "visual designer",
  ],
  "Software Architect": [
    "software architect",
    "solutions architect",
    "technical architect",
    "system architect",
    "chief architect",
    "מארכיטקט תוכנה",
  ],
  "R&D Management": [
    "r&d manager", "engineering manager", "vp engineering",
    "cto", "team lead", "ראש צוות", "מנהל פיתוח",
    "head of engineering", "director of engineering",
    "group manager",
  ],
  IT: [
    "it administrator",
    "system administrator",
    "sysadmin",
    "it manager",
    "network engineer",
    "it support engineer",
    "helpdesk engineer",
    "מנהל מערכות",
  ],
  Hardware: [
    "hardware engineer", "pcb", "vlsi", "fpga",
    "electrical engineer", "מהנדס חומרה",
    "chip design", "asic", "rtl",
  ],
  "Mechanical Engineering": [
    "mechanical engineer", "מהנדס מכונות",
    "mechanical design", "cad", "solidworks",
    "product engineering", "manufacturing engineer",
  ],
  "Project Management": [
    "project manager", "program manager", "pmo",
    "scrum master", "agile coach", "מנהל פרויקטים",
    "delivery manager", "technical project manager",
  ],
  "Data Analyst": [
    "data analyst", "business analyst", "bi analyst",
    "power bi", "tableau", "sql analyst", "analytics",
    "business intelligence", "מנתח נתונים",
  ],
  Sales: [
    "sales", "account executive", "business development",
    "מנהל מכירות", "bdr", "sdr", "sales engineer",
    "account manager", "sales representative",
  ],
  Marketing: [
    "marketing", "growth", "seo", "sem", "content",
    "brand manager", "מנהל שיווק", "digital marketing",
    "performance marketing", "growth hacker",
  ],
  HR: [
    "hr", "human resources", "recruiter", "talent acquisition",
    "מגייס", "משאבי אנוש", "people operations",
    "hr business partner", "hrbp",
  ],
  Finance: [
    "finance", "accountant", "controller", "cfo",
    "חשבונאות", "כלכלן", "financial analyst",
    "fp&a", "treasury",
  ],
  "Customer Success": [
    "customer success", "csm", "account manager",
    "customer support", "שירות לקוחות",
    "customer experience", "cx", "support engineer",
  ],
  Legal: [
    "legal", "lawyer", "attorney", "counsel",
    "עורך דין", "paralegal", "legal counsel",
    "corporate lawyer", "ip lawyer",
  ],
  "Student Jobs": [
    "student", "intern", "internship", "entry level",
    "סטודנט", "התמחות", "junior", "graduate",
    "trainee", "associate",
  ],
  Freelance: [
    "freelance", "contractor", "consultant", "independent",
    "עצמאי", "פרילנס",
  ],
  "Electrical Engineering": [
    "electrical engineer", "מהנדס חשמל", "power electronics",
    "signal processing", "embedded systems", "pcb design",
  ],
  Robotics: [
    "robotics", "robot", "ros", "autonomous", "automation",
    "mechatronics", "רובוטיקה",
  ],
  "Security Research": [
    "security researcher", "vulnerability researcher",
    "exploit developer", "reverse engineer",
    "malware analyst", "threat researcher",
  ],
  "Solution Engineering": [
    "solution engineer", "solutions engineer",
    "pre-sales engineer", "technical account manager",
    "sales engineer", "integration engineer",
  ],
  "Content Writing": [
    "content writer", "copywriter", "technical writer",
    "content manager", "editor", "content creator",
  ],
  Operations: [
    "operations", "ops manager", "business operations",
    "revenue operations", "revops", "growth operations",
  ],
  "Executive Roles": [
    "ceo", "cto", "coo", "cfo", "vp", "director",
    "head of", "chief", "executive", "president",
    "managing director",
  ],
}

export const LOCATIONS = [
  {
    value: "center",
    label: "Center",
    keywords: [
      "tel aviv", "tel aviv-yafo", "תל אביב", "ramat gan",
      "petah tikva", "rishon lezion", "bat yam", "holon",
      "bnei brak", "givatayim", "jaffa", "bat-yam",
    ],
  },
  {
    value: "gush_dan",
    label: "Gush Dan",
    keywords: [
      "tel aviv", "herzliya", "raanana", "ra'anana",
      "kfar saba", "netanya", "hod hasharon", "petah tikva",
      "rishon lezion", "rehovot", "lod", "ramla",
    ],
  },
  {
    value: "north",
    label: "North",
    keywords: [
      "haifa", "nazareth", "acre", "tiberias", "nahariya",
      "afula", "karmiel", "yokneam", "caesarea", "kiryat",
      "upper galilee", "lower galilee",
    ],
  },
  {
    value: "south",
    label: "South",
    keywords: [
      "beer sheva", "ashdod", "ashkelon", "eilat",
      "dimona", "beersheba", "negev", "kiryat gat",
    ],
  },
  {
    value: "jerusalem",
    label: "Jerusalem Area",
    keywords: [
      "jerusalem", "ירושלים", "modiin", "modi'in",
      "beit shemesh", "mevasseret",
    ],
  },
  {
    value: "sharon",
    label: "HaSharon",
    keywords: [
      "raanana", "ra'anana", "herzliya", "netanya",
      "hod hasharon", "kfar saba", "even yehuda",
      "tel mond", "kadima",
    ],
  },
  {
    value: "haifa",
    label: "Haifa Area",
    keywords: [
      "haifa", "tirat carmel", "nesher", "yokneam",
      "kiryat ata", "kiryat bialik", "kiryat motzkin",
      "kiryat yam", "acre", "nahariya",
    ],
  },
  {
    value: "remote",
    label: "Remote",
    keywords: [
      "remote", "מרחוק", "work from home", "wfh",
      "distributed", "fully remote",
    ],
  },
]

export const SENIORITY_LEVELS = [
  {
    value: "student",
    label: "Student / Intern",
    keywords: ["intern", "internship", "student", "סטודנט", "התמחות"],
  },
  {
    value: "entry",
    label: "Entry Level",
    keywords: ["entry", "entry level", "0-1", "no experience"],
  },
  {
    value: "junior",
    label: "Junior",
    keywords: ["junior", "jr", "1-3 years", "1-2 years"],
  },
  {
    value: "mid",
    label: "Mid Level",
    keywords: ["mid", "medior", "intermediate", "3-5 years"],
  },
  {
    value: "senior",
    label: "Senior",
    keywords: ["senior", "sr", "5+ years", "experienced"],
  },
  {
    value: "lead",
    label: "Team Lead / Staff",
    keywords: ["lead", "staff", "tech lead", "team lead", "ראש צוות"],
  },
  {
    value: "director",
    label: "Director+",
    keywords: ["director", "vp", "head of", "cto", "executive", "principal", "architect"],
  },
]
